### ISSUE TITLE
port listening on tcp6 but i don't have tcp6 ,how can i change to tcp?

### ISSUE THREAD

**Issue by 7feilee** [StratumAuhuur/CTFPad#1]
tcp6       0      0 :::1234                 :::*                    LISTEN     
tcp6       0      0 :::1235                 :::*                    LISTEN

**Comment by Kasalehlia** [comment]
I can not reproduce your problem. Please give the following information:
* operating system
* nodejs version
* config.json contents
* any changes you made to the source
